#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y mysql-server
service mysql start
mysql -e "CREATE DATABASE example;"
mysql -e "USE example; CREATE TABLE student(id int NOT NULL AUTO_INCREMENT, first_name varchar(50), last_name varchar(50), city varchar(50), semester int, PRIMARY KEY(id)); INSERT INTO student(first_name, last_name, city, semester) VALUES ('Juan', 'Perez', 'Cochabamba', 3),('Carlos', 'Lopez', 'La Paz',5);"
mysql -e "CREATE USER 'example_user'@'%' IDENTIFIED BY 'mysql';"
mysql -e "GRANT ALL ON example.* TO 'example_user'@'%';"
sed -i 's/bind-address.*/bind-address = 0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
